### ISSUE TITLE
关于如何使用docker-compose部署集群

### ISSUE THREAD

**Issue by linyihuiAble-dev** [openGemini/openGemini#857]
### Describe your question

```
FROM buildpack-deps:bookworm-curl

RUN export DEBIAN_FRONTEND=noninteractive && \
    # install dependencies \
    apt-get update -y && \
    apt-get install -y --no-install-recommends \
      ca-certificates \
      procps && \
    # cleanup apt \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV OPENGEMINI_VERSION 1.3.1

RUN ARCH= && dpkgArch="$(dpkg --print-architecture)" && \
    case "${dpkgArch##*-}" in \
      amd64) ARCH='amd64';; \
      arm64) ARCH='arm64';; \
      *)     echo "Unsupported architecture: ${dpkgArch}"; exit 1;; \
    esac && \
    wget --no-verbose --no-check-certificate https://github.com/openGemini/openGemini/releases/download/v${OPENGEMINI_VERSION}/openGemini-${OPENGEMINI_VERSION}-linux-${ARCH}.tar.gz && \
    tar zxvf openGemini-${OPENGEMINI_VERSION}-linux-${ARCH}.tar.gz --wildcards '*ts-*' && \
    mv usr/bin/ts-sql /usr/local/bin/ts-sql && \
    mv usr/bin/ts-meta /usr/local/bin/ts-meta && \
    mv usr/bin/ts-store /usr/local/bin/ts-store && \
    mv usr/bin/ts-monitor /usr/local/bin/ts-monitor && \
    mv usr/bin/ts-cli /usr/local/bin/ts-cli && \
    rm -f usr/bin/ts-* && \
    rm -f openGemini-${OPENGEMINI_VERSION}-linux-${ARCH}.tar.gz*

RUN chmod +x /usr/local/bin/ts-*

RUN mkdir -p /var/log/openGemini \
    && chmod ugo+Xrw -R /var/log/openGemini

ENV PATH="/usr/local/bin:${PATH}"
```

以上是我的Dockerfile

```
services:
  ts-meta1:
    image: opengemini:1.3.1
    container_name: ts-meta1
    hostname: ts-meta1
    command: ts-meta -config /etc/opengemini/conf/meta.conf
    volumes:
      - ./meta1/data:/var/lib/opengemini
      - ./meta1/config/meta.conf:/etc/opengemini/conf/meta.conf
    ports:
      - "8088:8088"  # meta.bind-address
      - "8091:8091"  # meta.http-bind-address
      - "8092:8092"  # meta.rpc-bind-address
      - "8010:8010"  # gossip.meta-bind-port
    networks:
      - opengemini_net

  ts-meta2:
    image: opengemini:1.3.1
    container_name: ts-meta2
    hostname: ts-meta2
    command: ts-meta -config /etc/opengemini/conf/meta.conf
    volumes:
      - ./meta2/data:/var/lib/opengemini
      - ./meta2/config/meta.conf:/etc/opengemini/conf/meta.conf
    ports:
      - "8188:8088"
      - "8191:8091"
      - "8192:8092"
      - "8110:8010"
    networks:
      - opengemini_net

  ts-meta3:
    image: opengemini:1.3.1
    container_name: ts-meta3
    hostname: ts-meta3
    command: ts-meta -config /etc/opengemini/conf/meta.conf
    volumes:
      - ./meta3/data:/var/lib/opengemini
      - ./meta3/config/meta.conf:/etc/opengemini/conf/meta.conf
    ports:
      - "8288:8088"
      - "8291:8091"
      - "8292:8092"
      - "8210:8010"
    networks:
      - opengemini_net

  ts-sql:
    image: opengemini:1.3.1
    container_name: ts-sql
    hostname: ts-sql
    command: ts-sql -config /etc/opengemini/conf/sql.conf
    volumes:
      - ./sql/config/sql.conf:/etc/opengemini/conf/sql.conf
    ports:
      - "8086:8086"  # http.bind-address
      - "8087:8087"  # http.flight-address
      - "8012:8012"  # gossip.sql-bind-port
    depends_on:
      - ts-meta1
      - ts-meta2
      - ts-meta3
    networks:
      - opengemini_net

  ts-store1:
    image: opengemini:1.3.1
    container_name: ts-store1
    hostname: ts-store1
    command: ts-store -config /etc/opengemini/conf/store.conf
    volumes:
      - ./store1/data:/var/lib/opengemini
      - ./store1/config/store.conf:/etc/opengemini/conf/store.conf
    ports:
      - "8400:8400"  # data.store-ingest-addr
      - "8401:8401"  # data.store-select-addr
      - "8011:8011"  # gossip.store-bind-port
    depends_on:
      - ts-meta1
      - ts-meta2
      - ts-meta3
    networks:
      - opengemini_net

  ts-store2:
    image: opengemini:1.3.1
    container_name: ts-store2
    hostname: ts-store2
    command: ts-store -config /etc/opengemini/conf/store.conf
    volumes:
      - ./store2/data:/var/lib/opengemini
      - ./store2/config/store.conf:/etc/opengemini/conf/store.conf
    ports:
      - "8500:8400"
      - "8501:8401"
      - "8111:8011"
    depends_on:
      - ts-meta1
      - ts-meta2
      - ts-meta3
    networks:
      - opengemini_net

networks:
  opengemini_net:
    driver: bridge
```

以上是我的docker-compose.yl文件

```
#!/bin/bash

# 创建目录结构
mkdir -p {meta1,meta2,meta3,store1,store2,sql}/config
mkdir -p {meta1,meta2,meta3,store1,store2}/data

# 生成meta配置
cat > meta1/config/meta.conf <<'EOF'
[common]
meta-join = ["ts-meta1:8092", "ts-meta2:8092", "ts-meta3:8092"]
pprof-enabled = true

[meta]
bind-address = "0.0.0.0:8088"
http-bind-address = "0.0.0.0:8091"
rpc-bind-address = "0.0.0.0:8092"
dir = "/var/lib/opengemini/meta"

[gossip]
enabled = true
bind-address = "0.0.0.0"
meta-bind-port = 8010
members = ["ts-meta1:8010", "ts-meta2:8010", "ts-meta3:8010"]

[logging]
path = "/var/log/opengemini/meta.log"
EOF

# 复制到其他meta节点
cp meta1/config/meta.conf meta2/config/
cp meta1/config/meta.conf meta3/config/

# 生成sql配置
cat > sql/config/sql.conf <<'EOF'
[common]
meta-join = ["ts-meta1:8092", "ts-meta2:8092", "ts-meta3:8092"]

[http]
bind-address = "0.0.0.0:8086"
flight-address = "0.0.0.0:8087"

[gossip]
enabled = true
bind-address = "0.0.0.0"
sql-bind-port = 8012

[logging]
path = "/var/log/opengemini/sql.log"
EOF

# 生成store配置
cat > store1/config/store.conf <<'EOF'
[common]
meta-join = ["ts-meta1:8092", "ts-meta2:8092", "ts-meta3:8092"]

[data]
store-ingest-addr = "0.0.0.0:8400"
store-select-addr = "0.0.0.0:8401"
store-data-dir = "/var/lib/opengemini/data"
store-wal-dir = "/var/lib/opengemini/wal"

[gossip]
enabled = true
bind-address = "0.0.0.0"
store-bind-port = 8011

[logging]
path = "/var/log/opengemini/store.log"
EOF

# 复制到其他store节点
cp store1/config/store.conf store2/config/
```

以上是创建配置文件命令

问题1：这样的形式部署集群是否可行？

问题2：docker-compose up -d之后，我的meta容器无法启动
```
root@ubuntu:/opt/opengemini-docker/opengemini-cluster/1.3.1# docker logs -f 7de8a9c078a4
parse config: gossip bind-port must be greater than 0. got: 0
```
但是我的[gossip]中的meta-bind-port参数确实不为0的
